### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by COD1EINE** [Antpap07/tikhack#1]
I'd really like to use this tool but the problem is I don't have a Linux Machine. Could you possibly make a windows version?

**Comment by vidgix** [comment]
> I'd really like to use this tool but the problem is I don't have a Linux Machine. Could you possibly make a windows version?

sometimes u need kali, sometimes u need windows

**Comment by Antpap07** [comment]
Just use subsystem for windows. It's not ready yet tho

**Comment by pablo11234** [comment]
guys how to run it . it give a error [   File "/home/kali/tikhack/setup.py", line 1
    import.os
          ^
SyntaxError: invalid syntax
]

**Comment by Antpap07** [comment]
Mate it's not ready yet you can't really run it without coding knowledge

**Comment by kingBeachboi** [comment]
How do I run and use this, i have it installed

**Comment by jnamason** [comment]
I have a working copy for anyone that wants this tool.   The script was a mess when i cloned it.  So I decided to reconfigure it into a proper working copy.   Shot me an email if interested.   ohnokali@proton.me

**Comment by jnamason** [comment]
> How do I run and use this, i have it installed

send me a message.  If your using this package it wont work unless you rewrote it like i did.

**Comment by jnamason** [comment]
I also fixed Faitagram and have a working copy.    Also I'm running Kali Purple, but with a few modification I can step you threw, you can also have it up and running on your Linux Machine.
